
package Client_Side.Web_DDO;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Clinic_DDO_ImplService", targetNamespace = "http://Server_DDO.Server_Side/", wsdlLocation = "http://localhost:9003/server_ddo?wsdl")
public class ClinicDDOImplService
    extends Service
{

    private final static URL CLINICDDOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLINICDDOIMPLSERVICE_EXCEPTION;
    private final static QName CLINICDDOIMPLSERVICE_QNAME = new QName("http://Server_DDO.Server_Side/", "Clinic_DDO_ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9003/server_ddo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLINICDDOIMPLSERVICE_WSDL_LOCATION = url;
        CLINICDDOIMPLSERVICE_EXCEPTION = e;
    }

    public ClinicDDOImplService() {
        super(__getWsdlLocation(), CLINICDDOIMPLSERVICE_QNAME);
    }

    public ClinicDDOImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLINICDDOIMPLSERVICE_QNAME, features);
    }

    public ClinicDDOImplService(URL wsdlLocation) {
        super(wsdlLocation, CLINICDDOIMPLSERVICE_QNAME);
    }

    public ClinicDDOImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLINICDDOIMPLSERVICE_QNAME, features);
    }

    public ClinicDDOImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClinicDDOImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClinicServersInterface
     */
    @WebEndpoint(name = "Clinic_DDO_ImplPort")
    public ClinicServersInterface getClinicDDOImplPort() {
        return super.getPort(new QName("http://Server_DDO.Server_Side/", "Clinic_DDO_ImplPort"), ClinicServersInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClinicServersInterface
     */
    @WebEndpoint(name = "Clinic_DDO_ImplPort")
    public ClinicServersInterface getClinicDDOImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Server_DDO.Server_Side/", "Clinic_DDO_ImplPort"), ClinicServersInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLINICDDOIMPLSERVICE_EXCEPTION!= null) {
            throw CLINICDDOIMPLSERVICE_EXCEPTION;
        }
        return CLINICDDOIMPLSERVICE_WSDL_LOCATION;
    }

}
